CREATE TABLE IF NOT EXISTS `TRANSACTION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(30) NOT NULL,
  `PRICE` INT(11) NOT NULL,
  PRIMARY KEY (`id`)
  ) ENGINE=InnoDB AUTO_INCREMENT=1000000000;