CREATE TABLE IF NOT EXISTS `USER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`)
  ) ENGINE=InnoDB AUTO_INCREMENT=1000000000;

INSERT INTO USER(USER_NAME) VALUES ('stunstunstun')